services:
  backend:
    build: ./backened
    container_name: backened
    image: vansh967/backend2
    ports:
      - "4000:4000"  # Ensure both internal and external ports are 4000
    networks:
      - app-network
    env_file:
      - backened/.env

  frontend:
    build: ./frontened  # Corrected folder name
    container_name: frontend
    image: vansh967/frontend2
    ports:
      - "5174:5174"
    networks:
      - app-network
    depends_on:
      - backend

  admin:
    build: ./admin
    container_name: admin
    image: vansh967/admin2
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
